<?php
namespace App\Command;

use App\Entity\AdviceArticle;
use App\Repository\AdviceArticleRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

#[AsCommand(name:'app:seed-advice', description:'Installe les premiers conseils FyraCare')]
final class SeedAdviceArticlesCommand extends Command
{
    public function __construct(private EntityManagerInterface $em, private AdviceArticleRepository $articles) { parent::__construct(); }
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $items = $this->items();
        foreach ($items as $index => $data) {
            $article=$this->articles->findOneBy(['slug'=>$data['slug']]) ?? new AdviceArticle();
            $article->setSlug($data['slug'])->setCategory($data['category'])->setTitleFr($data['fr'][0])->setExcerptFr($data['fr'][1])->setContentFr($data['fr'][2])->setSeoTitleFr($data['fr'][3])->setSeoDescriptionFr($data['fr'][4])->setTitleEn($data['en'][0])->setExcerptEn($data['en'][1])->setContentEn($data['en'][2])->setSeoTitleEn($data['en'][3])->setSeoDescriptionEn($data['en'][4])->setTitleAr($data['ar'][0])->setExcerptAr($data['ar'][1])->setContentAr($data['ar'][2])->setSeoTitleAr($data['ar'][3])->setSeoDescriptionAr($data['ar'][4])->setPublished(true)->setFeatured($index < 3)->setPublishedAt(new \DateTimeImmutable(sprintf('2026-08-%02d 09:00:00', 17 + $index)))->setUpdatedAt(new \DateTimeImmutable());
            $this->em->persist($article);
        }
        $this->em->flush();
        $output->writeln('<info>Cinq conseils FyraCare ont été installés.</info>');
        return Command::SUCCESS;
    }
    private function items(): array
    {
        return [
            ['slug'=>'bien-se-preparer-a-la-naissance','category'=>'birth-preparation','fr'=>['Bien se préparer à la naissance','Comprendre les étapes et acquérir des repères concrets aide à aborder la naissance avec davantage de confiance.',"La préparation à la naissance permet de mieux comprendre les changements de la grossesse, le déroulement du travail et les premiers jours avec bébé. Elle associe des informations claires à des exercices pratiques adaptés à chaque femme.\n\nAu fil des séances, vous pouvez découvrir la respiration, les positions qui favorisent le confort, les techniques de poussée et les premières bases de l’allaitement. C’est aussi un espace pour poser vos questions, exprimer vos inquiétudes et associer votre accompagnant au projet de naissance.\n\nIl n’existe pas une seule manière de bien se préparer. L’accompagnement doit tenir compte de votre santé, de votre histoire et des recommandations de l’équipe qui suit votre grossesse. Chez FyraCare, les séances sont personnalisées pour vous aider à construire des repères réalistes et rassurants.",'Préparation à la naissance à Nouakchott — Conseils FyraCare','Découvrez comment les cours de préparation à la naissance FyraCare vous aident à mieux comprendre la grossesse, le travail et les premiers jours avec bébé.'],'en'=>['Preparing well for birth','Understanding the stages and learning practical tools can help you approach birth with greater confidence.',"Birth preparation helps you understand pregnancy changes, labour and the first days with your baby. It combines clear information with practical exercises adapted to each woman.\n\nSessions may cover breathing, comfortable positions, pushing techniques and the first foundations of breastfeeding. They also provide a safe space for questions and concerns, and can help involve your birth partner.\n\nThere is no single right way to prepare. Support should reflect your health, your story and the recommendations of your maternity team. FyraCare sessions are personalised to help you build realistic and reassuring reference points.",'Birth preparation in Nouakchott — FyraCare advice','Learn how FyraCare birth preparation sessions can help you understand pregnancy, labour and the first days with your baby.'],'ar'=>['الاستعداد الجيد للولادة','يساعد فهم المراحل واكتساب أدوات عملية على استقبال الولادة بثقة أكبر.',"يساعد التحضير للولادة على فهم تغيرات الحمل ومراحل المخاض والأيام الأولى مع المولود، ويجمع بين المعلومات الواضحة والتمارين العملية الملائمة لكل امرأة.\n\nيمكن أن تشمل الجلسات التنفس والوضعيات المريحة وتقنيات الدفع والمبادئ الأولى للرضاعة الطبيعية، كما توفر مساحة آمنة لطرح الأسئلة ومشاركة المخاوف وإشراك المرافق.\n\nلا توجد طريقة واحدة صحيحة للاستعداد. يجب أن تراعي المرافقة حالتك الصحية وتجربتك وتوصيات الفريق المتابع للحمل. تقدم FyraCare جلسات شخصية لبناء مرجعيات واقعية ومطمئنة.",'التحضير للولادة في نواكشوط — نصائح FyraCare','تعرّفي على دور جلسات FyraCare في فهم الحمل والمخاض والأيام الأولى مع المولود.']],
            ['slug'=>'massage-prenatal-un-moment-pour-soi','category'=>'wellbeing','fr'=>['Massage prénatal : un moment pour soi','À partir du quatrième mois, un massage adapté peut offrir détente et confort pendant la grossesse.',"La grossesse transforme progressivement la posture et peut s’accompagner de fatigue ou de tensions musculaires. Le massage prénatal proposé par FyraCare est conçu comme un moment de détente pour la future maman, dans une installation confortable et respectueuse de son corps.\n\nLes gestes, la durée et les zones travaillées sont adaptés à l’avancement de la grossesse et à votre ressenti. Le dialogue avec la praticienne reste essentiel : signalez toute gêne, douleur ou recommandation particulière donnée par votre professionnel de santé.\n\nChez FyraCare, ce soin est proposé à partir du quatrième mois. Il contribue au bien-être, mais ne remplace ni le suivi prénatal ni l’évaluation d’un symptôme inhabituel.",'Massage prénatal à Nouakchott : bienfaits et précautions — FyraCare','Découvrez l’approche douce du massage prénatal FyraCare à partir du quatrième mois de grossesse.'],'en'=>['Prenatal massage: time for yourself','From the fourth month, an adapted massage can provide relaxation and comfort during pregnancy.',"Pregnancy gradually changes posture and may bring fatigue or muscle tension. FyraCare prenatal massage is designed as a relaxing moment for the mother-to-be, with comfortable positioning that respects her body.\n\nMovements, duration and treated areas are adapted to the stage of pregnancy and to how you feel. Dialogue with the practitioner is essential: mention any discomfort, pain or specific advice from your healthcare professional.\n\nFyraCare offers this care from the fourth month. It supports wellbeing but does not replace prenatal follow-up or assessment of an unusual symptom.",'Prenatal massage in Nouakchott — FyraCare','Discover FyraCare’s gentle prenatal massage approach from the fourth month of pregnancy.'],'ar'=>['تدليك ما قبل الولادة: وقت لكِ','ابتداءً من الشهر الرابع، يمكن للتدليك الملائم أن يمنح الحامل الراحة والاسترخاء.',"يغير الحمل وضعية الجسم تدريجياً وقد يصاحبه تعب أو توتر عضلي. صُمم تدليك FyraCare للحامل ليكون لحظة استرخاء في وضعية مريحة تحترم جسدها.\n\nتُكيّف الحركات والمدة والمناطق المعالجة حسب مرحلة الحمل وشعورك. من المهم إبلاغ الممارسة بأي انزعاج أو ألم أو توصية خاصة من مهني الصحة.\n\nيُقدم هذا التدليك في FyraCare ابتداءً من الشهر الرابع. وهو يدعم الرفاه ولا يعوض متابعة الحمل أو تقييم أي عرض غير معتاد.",'تدليك الحوامل في نواكشوط — FyraCare','اكتشفي أسلوب FyraCare اللطيف في تدليك الحوامل ابتداءً من الشهر الرابع.']],
            ['slug'=>'preparer-son-perinee-avant-accouchement','category'=>'pelvic-health','fr'=>['Préparer son périnée avant l’accouchement','Mieux connaître cette zone aide à adopter des gestes doux et à se préparer avec confiance.',"Le périnée joue un rôle important dans le soutien des organes, la continence et la vie intime. Pendant la grossesse, apprendre à le localiser, à le relâcher et à mieux comprendre son fonctionnement peut être utile pour la préparation à la naissance.\n\nLe massage périnéal est un geste très doux qui peut être enseigné au centre afin que vous puissiez ensuite le pratiquer à domicile dans de bonnes conditions. Il ne doit jamais être douloureux ni réalisé sans explications adaptées.\n\nAvant de commencer, parlez-en à votre sage-femme, particulièrement si votre grossesse nécessite une surveillance ou si vous ressentez une douleur. FyraCare propose une séance d’apprentissage ou des packs de plusieurs séances selon vos besoins.",'Préparation du périnée à Nouakchott — Conseils FyraCare','Comprendre le périnée et apprendre des gestes doux avant l’accouchement avec l’accompagnement FyraCare.'],'en'=>['Preparing your pelvic floor before birth','Understanding this area helps you use gentle techniques and prepare with confidence.',"The pelvic floor supports organs and contributes to continence and intimate health. During pregnancy, learning to locate and relax it can be useful when preparing for birth.\n\nPerineal massage is a very gentle technique that can be taught at the centre so that you can practise safely at home. It should never be painful or attempted without suitable guidance.\n\nTalk to your midwife before beginning, especially if your pregnancy needs additional monitoring or if you experience pain. FyraCare offers a learning session or a series of sessions according to your needs.",'Pelvic-floor preparation in Nouakchott — FyraCare','Understand the pelvic floor and learn gentle preparation techniques before birth with FyraCare.'],'ar'=>['تحضير العجان قبل الولادة','يساعد فهم هذه المنطقة على اعتماد حركات لطيفة والاستعداد بثقة.',"يلعب قاع الحوض دوراً مهماً في دعم الأعضاء والتحكم والصحة الحميمة. خلال الحمل، قد يكون تعلم تحديد هذه العضلات وإرخائها مفيداً للتحضير للولادة.\n\nتدليك العجان تقنية لطيفة جداً يمكن تعلمها في المركز ثم ممارستها في المنزل بطريقة سليمة. يجب ألا تكون مؤلمة ولا تُمارس دون إرشادات مناسبة.\n\nتحدثي مع القابلة قبل البدء، خاصة إذا كان الحمل يتطلب متابعة إضافية أو عند وجود ألم. تقدم FyraCare جلسة تعليمية أو مجموعة جلسات حسب الحاجة.",'تحضير العجان في نواكشوط — FyraCare','تعرّفي على قاع الحوض وتعلمي تقنيات لطيفة للتحضير للولادة مع FyraCare.']],
            ['slug'=>'allaitement-quand-demander-aide','category'=>'breastfeeding','fr'=>['Allaitement : quand demander de l’aide ?','Une difficulté persistante, une douleur ou des doutes peuvent justifier une consultation personnalisée.',"Les débuts de l’allaitement sont une période d’apprentissage pour la mère comme pour le bébé. Des questions sur la position, la prise du sein, le rythme des tétées ou le confort sont fréquentes. Demander de l’aide tôt permet souvent de mieux comprendre la situation.\n\nUne consultation commence par un entretien sur votre projet, votre santé et votre quotidien avec bébé. Une tétée peut ensuite être observée afin de proposer des ajustements adaptés. Consultez rapidement un professionnel de santé si vous êtes inquiète pour l’état de votre bébé, son alimentation, ou si vous présentez une douleur importante ou un symptôme inhabituel.\n\nL’objectif n’est pas d’imposer une méthode, mais de vous aider à faire des choix éclairés et compatibles avec votre situation.",'Consultation allaitement à Nouakchott — FyraCare','Quand consulter pour l’allaitement ? FyraCare vous accompagne avec une écoute personnalisée de la mère et du bébé.'],'en'=>['Breastfeeding: when should you ask for help?','Persistent difficulty, pain or uncertainty may justify personalised support.',"The beginning of breastfeeding is a learning period for both mother and baby. Questions about positioning, latch, feeding rhythm or comfort are common. Asking for help early can make the situation easier to understand.\n\nA consultation begins with a conversation about your goals, health and daily life with your baby. A feed may then be observed to suggest suitable adjustments. Seek prompt medical advice if you are worried about your baby’s condition or feeding, or if you experience significant pain or an unusual symptom.\n\nThe goal is not to impose one method, but to help you make informed choices that fit your situation.",'Breastfeeding consultation in Nouakchott — FyraCare','When should you seek breastfeeding support? FyraCare offers personalised care for mother and baby.'],'ar'=>['الرضاعة الطبيعية: متى تطلبين المساعدة؟','قد تستدعي الصعوبة المستمرة أو الألم أو الشكوك استشارة شخصية.',"تمثل بداية الرضاعة فترة تعلم للأم والطفل. من الطبيعي طرح أسئلة حول الوضعية والتقام الثدي وإيقاع الرضعات والراحة. طلب المساعدة مبكراً قد يسهل فهم الوضع.\n\nتبدأ الاستشارة بحوار حول مشروعك وصحتك وحياتك اليومية مع الطفل، ثم يمكن ملاحظة رضعة واقتراح تعديلات مناسبة. اطلبي تقييماً طبياً سريعاً إذا قلقتِ بشأن حالة الطفل أو تغذيته، أو عند وجود ألم شديد أو عرض غير معتاد.\n\nالهدف ليس فرض طريقة واحدة، بل مساعدتك على اتخاذ خيارات واعية تناسب وضعك.",'استشارة الرضاعة في نواكشوط — FyraCare','متى تحتاجين إلى دعم في الرضاعة؟ تقدم FyraCare مرافقة شخصية للأم والطفل.']],
            ['slug'=>'reeducation-perineale-apres-accouchement','category'=>'postpartum','fr'=>['Rééducation périnéale après l’accouchement','Une évaluation personnalisée aide à reprendre progressivement et à respecter le rythme du corps.',"Après l’accouchement, le périnée et la sangle abdominale ont besoin de temps et d’une reprise progressive. La rééducation périnéale vise à retrouver une meilleure conscience musculaire, du tonus et du confort au quotidien. Elle peut également concerner les femmes ayant accouché par césarienne.\n\nChez FyraCare, l’accompagnement commence généralement six à huit semaines après l’accouchement, selon votre récupération et l’avis du professionnel qui vous suit. Le travail du périnée précède habituellement la rééducation abdominale.\n\nUne sensation de pesanteur, des fuites, des tensions ou des douleurs méritent une évaluation individualisée. Évitez de reprendre seule des exercices intenses si vous ne savez pas encore ce qui est adapté à votre situation.",'Rééducation périnéale post-partum à Nouakchott — FyraCare','Découvrez quand et comment reprendre progressivement la rééducation périnéale après l’accouchement avec FyraCare.'],'en'=>['Pelvic-floor rehabilitation after birth','A personalised assessment helps you resume gradually and respect your body’s pace.',"After birth, the pelvic floor and abdominal wall need time and a gradual return to activity. Pelvic-floor rehabilitation aims to rebuild muscle awareness, tone and everyday comfort. It may also benefit women who gave birth by caesarean section.\n\nAt FyraCare, support generally begins six to eight weeks after birth, depending on your recovery and the advice of your healthcare professional. Pelvic-floor work usually comes before abdominal rehabilitation.\n\nHeaviness, leakage, tension or pain deserve an individual assessment. Avoid restarting intense exercises alone if you are unsure what is suitable for your situation.",'Postpartum pelvic-floor rehabilitation in Nouakchott — FyraCare','Learn when and how to resume pelvic-floor rehabilitation gradually after birth with FyraCare.'],'ar'=>['إعادة تأهيل قاع الحوض بعد الولادة','يساعد التقييم الشخصي على استئناف النشاط تدريجياً واحترام إيقاع الجسم.',"بعد الولادة، يحتاج قاع الحوض وعضلات البطن إلى وقت وعودة تدريجية للنشاط. تهدف إعادة التأهيل إلى تحسين الوعي العضلي والتوتر والراحة اليومية، وقد تفيد أيضاً بعد الولادة القيصرية.\n\nتبدأ المرافقة في FyraCare عادة بعد ستة إلى ثمانية أسابيع من الولادة حسب التعافي ورأي مهني الصحة المتابع. يسبق عمل قاع الحوض عادة إعادة تأهيل البطن.\n\nيستحق الشعور بالثقل أو التسرب أو التوتر أو الألم تقييماً فردياً. تجنبي استئناف التمارين الشديدة وحدك إذا لم تعرفي ما يناسب حالتك.",'إعادة تأهيل قاع الحوض بعد الولادة في نواكشوط — FyraCare','تعرّفي على وقت وكيفية استئناف إعادة تأهيل قاع الحوض تدريجياً بعد الولادة مع FyraCare.']],
        ];
    }
}
